### PR TITLE
Docker partial events merging correctness

### PR DESCRIPTION
**Pull request by MOZGIII**
This is a second PR, cause I screwed up the first one.

### CODE REVIEW

**Comment by MOZGIII** [comment]
This test currently fails, and still needs some polishing, but I guess what I currently have is ready for a review.

**Comment by binarylogic** [comment]
Also, once this is merged and passing I'd like to add it to our marketing pages that expose the correctness tests.

**Comment by MOZGIII** [comment]
Everything is resolved now, I'm merging the PR :tada: 
Newly introduced correctness test *should* still fail until `vector` ships a version that includes docker partial message merging.

**Comment by binarylogic** [comment]
Nice!

**Pull request merged**
