### PR TITLE
chore: Add new Ansible aws_ec2 inventory plugin

### PR DESCRIPTION
**Pull request by binarylogic**
Every time I use Ansible something is broken and I have to sift through terrible documentation to try and fix it. This is one of those cases. The old way of enabling dynamic inventory in Ansible appears to be discontinued and they recommend using the new `aws_ec2` plugin. I attempted to follow:

1. https://docs.ansible.com/ansible/latest/collections/amazon/aws/aws_ec2_inventory.html
2. https://medium.com/faun/learning-the-ansible-aws-ec2-dynamic-inventory-plugin-59dd6a929c7f

I was unable to get this hooked up. So instead of wasting more time I'm throwing this up in a PR until I can get back to it.

### CODE REVIEW

**Comment by jamtur01** [comment]
@binarylogic This okay to merge?

**Comment by binarylogic** [comment]
I wish. I have no idea how to get the new ec2 inventory plugin to work with Ansible. Ansible is a house of cards.

**Comment by jamtur01** [comment]
Should have used Puppet... 🥇

**Comment by jszwedko** [comment]
This fixes the inventory and also updates the test configuration so that they all run successfully. It did spawn #58 though as some of the changes were related to config files which means the tests won't be runnable with older vector versions.

**Pull request merged**
